import Link from "next/link";import {notFound} from "next/navigation";import {Check,MapPinned,Wifi,Phone,ShieldCheck,Waves,Gamepad2,Cigarette,ShoppingBag,LogIn,Utensils,BedDouble,Clock3} from "lucide-react";import {PageShell} from "@/components/PageShell";import {guide} from "@/data/campusGuide";
const routes:Record<string,string>={accommodation:"Accommodation",dining:"Dining",pool:"Swimming Pool",entertainment:"Entertainment & Common Room",dress-code:"Dress Code",smoking:"Smoking Area",access:"Entering & Leaving Campus",safety:"Safety & Security",wifi:"Wi-Fi & Communication",police-shop:"Police Shop",map:"Campus Map",facilities:"Facilities",essentials:"Essentials"};
export function generateStaticParams(){return Object.keys(routes).map(section=>({section}))}
export default async function Section({params}:{params:Promise<{section:string}>}){const {section}=await params;if(!routes[section])notFound();
if(section==='facilities')return <PageShell title="Facilities" eyebrow="Around campus"><div className="mt-6 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{guide.facilities.map(f=><Link href={f.id==='sports'?'/explore':`/${f.id}`} key={f.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-ncple-50 text-ncple-700"><BuildingIcon id={f.id}/></div><h2 className="mt-4 font-semibold text-slate-900">{f.name}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{f.description}</p><span className="mt-4 inline-block text-sm font-semibold text-ncple-700">View details →</span></Link>)}</div></PageShell>;
if(section==='essentials')return <PageShell title="Essentials" eyebrow="Important information"><div className="mt-6 grid gap-3 md:grid-cols-2">{[['/access','Entering & Leaving Campus','Gate procedures and access information.'],['/safety','Safety & Security','Your safety is important to us.'],['/wifi','Wi-Fi & Communication','Connect using the PII-Guest network.'],['/checkout','Before You Check Out','Complete the departure checklist.']].map(([href,t,d])=><Link href={href} key={href} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><h2 className="font-semibold text-slate-900">{t}</h2><p className="mt-2 text-sm text-slate-500">{d}</p></Link>)}</div></PageShell>;
if(section==='map')return <PageShell title="Campus Map" eyebrow="Find your way around"><div className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-soft"><div className="flex min-h-80 items-center justify-center bg-ncple-50 p-8 text-center"><div><MapPinned className="mx-auto text-ncple-700" size={44}/><h2 className="mt-4 text-xl font-bold text-ncple-950">Campus map coming soon</h2><p className="mt-2 max-w-lg text-sm leading-6 text-slate-500">No actual map image is present in the source material, so no geographic map is fabricated. This area is ready for the official map asset.</p></div></div><div className="grid gap-2 p-5 sm:grid-cols-2 lg:grid-cols-3">{guide.mapLocations.map(x=><div key={x} className="rounded-xl bg-slate-50 px-4 py-3 text-sm font-medium text-slate-700">{x}</div>)}</div></div></PageShell>;
if(section==='accommodation')return <PageShell title="Your Accommodation" eyebrow="During your stay"><div className="mt-6 rounded-3xl bg-ncple-900 p-7 text-white"><BedDouble size={30}/><p className="mt-5 text-sm text-blue-100">Accommodation is provided at</p><p className="mt-1 text-2xl font-bold">Edhuru Hiya & Guest House</p></div><div className="mt-6 grid gap-3">{guide.accommodationChecklist.map(x=><div key={x} className="flex gap-3 rounded-2xl bg-white p-4 shadow-soft"><Check className="text-ncple-700" size={20}/><span className="text-sm leading-6 text-slate-700">{x}</span></div>)}</div></PageShell>;
if(section==='dining')return <PageShell title="Dining Information" eyebrow="Meal schedule"><div className="mt-6 grid gap-3 md:grid-cols-3">{guide.dining.map(m=><div key={m.meal} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-soft"><Utensils className="text-ncple-700" size={25}/><p className="mt-6 text-xs font-bold tracking-[.16em] text-ncple-500">{m.meal}</p><p className="mt-1 text-2xl font-bold text-ncple-950">{m.time}</p><p className="mt-3 text-sm leading-6 text-slate-500">{m.location}</p></div>)}</div></PageShell>;
if(section==='pool')return <PageShell title="Swimming Pool" eyebrow="Sports & recreation"><div className="mt-6 rounded-3xl bg-ncple-900 p-7 text-white"><Waves size={30}/><p className="mt-5 text-sm text-blue-100">Daily opening hours</p><p className="text-3xl font-bold">06:00 – 19:00</p></div><RuleList title="Pool Rules" items={guide.poolRules}/></PageShell>;
if(section==='entertainment')return <PageShell title="Entertainment & Common Room" eyebrow="Relax and unwind"><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-soft"><Gamepad2 className="text-ncple-700" size={30}/><p className="mt-5 text-sm text-slate-500">Opening hours</p><p className="text-2xl font-bold text-ncple-950">08:00 – 23:00 daily</p><div className="mt-5 flex flex-wrap gap-2">{['Pool','Karaoke','Carrom','Other games'].map(x=><span key={x} className="rounded-full bg-ncple-50 px-3 py-2 text-sm font-medium text-ncple-900">{x}</span>)}</div></div><RuleList title="Rules" items={guide.entertainmentRules}/></PageShell>;
if(section==='dress-code')return <PageShell title="Dress Code" eyebrow="What to wear"><div className="mt-6 grid gap-3">{guide.dressCode.map(x=><div key={x.title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><h2 className="font-semibold text-ncple-950">{x.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{x.body}</p></div>)}</div></PageShell>;
if(section==='smoking')return <PageShell title="Smoking Area" eyebrow="Campus rule"><div className="mt-6 rounded-3xl bg-ncple-900 p-7 text-white"><Cigarette size={30}/><p className="mt-5 text-xl font-bold">{guide.smoking.message}</p><p className="mt-3 text-sm text-blue-100">Location: {guide.smoking.location}</p></div><RuleList title="Rules" items={guide.smoking.rules}/></PageShell>;
if(section==='access')return <PageShell title="Entering & Leaving the Campus" eyebrow="Campus access"><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-soft"><LogIn className="text-ncple-700" size={30}/><h2 className="mt-4 text-xl font-bold text-ncple-950">When leaving or returning</h2><ol className="mt-5 space-y-3">{guide.campusAccess.map((x,i)=><li key={x} className="flex gap-3 text-sm leading-6 text-slate-700"><span className="font-bold text-ncple-700">{i+1}.</span>{x}</li>)}</ol></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{guide.gates.map(x=><div key={x} className="rounded-2xl bg-ncple-50 p-5 font-semibold text-ncple-950">{x}</div>)}</div></PageShell>;
if(section==='safety')return <PageShell title="Safety & Security" eyebrow="Stay aware"><div className="mt-6 rounded-3xl bg-ncple-900 p-7 text-white"><ShieldCheck size={32}/><h2 className="mt-5 text-2xl font-bold">Your safety is important to us.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-blue-50">{guide.safety}</p></div></PageShell>;
if(section==='wifi')return <PageShell title="Wi-Fi & Communication" eyebrow="Stay connected"><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-7 shadow-soft"><Wifi className="text-ncple-700" size={32}/><p className="mt-6 text-xs font-bold tracking-[.16em] text-slate-400">NETWORK</p><p className="text-2xl font-bold text-ncple-950">{guide.wifi.network}</p><p className="mt-5 text-xs font-bold tracking-[.16em] text-slate-400">PASSWORD</p><p className="mt-1 text-sm text-slate-600">{guide.wifi.password}</p></div></PageShell>;
if(section==='police-shop')return <PageShell title="Police Shop" eyebrow="Everyday essentials"><div className="mt-6 rounded-3xl border border-slate-200 bg-white p-7 shadow-soft"><ShoppingBag className="text-ncple-700" size={30}/><p className="mt-5 text-xl font-bold text-ncple-950">Everyday essentials</p><div className="mt-4 flex flex-wrap gap-2">{['Cosmetics','Toiletries','Snacks','More'].map(x=><span key={x} className="rounded-full bg-ncple-50 px-3 py-2 text-sm font-medium text-ncple-900">{x}</span>)}</div><p className="mt-6 text-sm font-semibold text-slate-700">09:00 – 13:00</p><p className="text-sm font-semibold text-slate-700">21:00 – 23:00</p></div></PageShell>;
return null;}
function RuleList({title,items}:{title:string;items:readonly string[]}){return <section className="mt-7"><h2 className="text-xl font-bold text-ncple-950">{title}</h2><div className="mt-3 grid gap-3">{items.map(x=><div key={x} className="flex gap-3 rounded-2xl bg-white p-4 shadow-soft"><Check className="mt-0.5 shrink-0 text-ncple-700" size={19}/><p className="text-sm leading-6 text-slate-700">{x}</p></div>)}</div></section>}
function BuildingIcon({id}:{id:string}){return id==='pool'?<Waves size={21}/>:id==='entertainment'?<Gamepad2 size={21}/>:id==='shop'?<ShoppingBag size={21}/>:id==='accommodation'?<BedDouble size={21}/>:id==='dining'?<Utensils size={21}/>:<MapPinned size={21}/>}
